# Generated by Django 4.2.30 on 2026-04-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('researcher', 'Researcher')], default='user', max_length=20),
        ),
    ]
