# Generated by Django 4.2.30 on 2026-04-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=20)),
                ('condition', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn')], default='Enrolled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='studies.study')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
